### ISSUE TITLE
What is this repository?

### ISSUE THREAD

**Issue by danfowler** [datatxt/jsonx#1]

**Comment by geraldb** [comment]
@danfowler  Can you expand on "What is this repository?" - what do you want to ask? Sorry I don't understand your question. Cheers.

PS: If you want to ask if that's the home of the new JSON w/ Extensions format than, yes, that is the new home of the format and spec with examples etc. 

**(Update)** Added the following question (and answer) to the README:

> **Q: What's JSON with Extensions? Why? Why?**
>
> JSON with Extensions (JSONX) is a new JSON format evolved for humans, that is,
> the goal of the JSON extensions is making writing and reading JSON easier for you (dear human). 
> JSON is no longer used as a machine-to-machine data interchange format only, thus, let's make it more
> human-friendly.

**Comment by danfowler** [comment]
@geraldb thanks!  Now I understand! 👍

**Comment by geraldb** [comment]
@danfowler  Thanks for your interest in JSON w/ Extensions. Keep up the great work on frictionless data (tabular data packages w/ json, etc.). Cheers.
